name: Build and Push to OCIR

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      OCIR_REGION: ${{ secrets.OCIR_REGION }}
      OCIR_USERNAME: ${{ secrets.OCIR_USERNAME }}
      OCIR_PASSWORD: ${{ secrets.OCIR_PASSWORD }}
      OCIR_NAMESPACE: ${{ secrets.OCIR_NAMESPACE }}
      OCIR_REPO_NAME: ${{ secrets.OCIR_REPO_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 환경 변수 확인
        run: |
          echo "OCIR_REGION: ${{ env.OCIR_REGION }}"
          echo "OCIR_USERNAME: ${{ env.OCIR_USERNAME }}"
          echo "---"
          echo "이미지 태그: ${{ env.OCIR_REGION }}/${{ env.OCIR_NAMESPACE }}/${{ env.OCIR_REPO_NAME }}:latest"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to OCIR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.OCIR_REGION }}               # ap-chuncheon-1.ocir.io
          username: ${{ env.OCIR_USERNAME }}             # <namespace>/<user>
          password: ${{ env.OCIR_PASSWORD }}             # Auth Token

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.OCIR_REGION }}/${{ env.OCIR_NAMESPACE }}/${{ env.OCIR_REPO_NAME }}:latest
